
# 서버 설정
server:
  port: 9000

# spring 설정
spring:
  devtools:
    livereload:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: userService

# Eureka 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

# config 설정
mybatis:
  config-location: classpath:config/myBatis.xml



